lang: english

plugin-prefix: "[&b&lGuilds] "

allow-guild-damage: false
allow-ally-damage: false


#-----------------------------------------------------------#
#                        Role Configuration                 #
#-----------------------------------------------------------#

roles:
  0:
    name: "GuildMaster"
    permission-node: "guilds.role.master"
    permissions:
      activate-buff: true
      add-ally: true
      ally-chat: true
      change-home: true
      change-prefix: true
      chat: true
      demote: true
      deposit-money: true
      invite: true
      kick: true
      open-vault: true
      promote: true
      remove-ally: true
      remove-guild: true
      toggle-guild: true
      transfer-guild: true
      upgrade-guild: true
      withdraw-money: true
      claim-land: true
      unclaim-land: true
      destroy: true
      place: true
      interact: true

  1:
    name: "Officer"
    permission-node: "guilds.role.officer"
    permissions:
      activate-buff: false
      add-ally: true
      ally-chat: true
      change-home: true
      change-prefix: false
      chat: true
      demote: true
      deposit-money: true
      invite: true
      kick: true
      open-vault: true
      promote: true
      remove-ally: true
      remove-guild: false
      toggle-guild: false
      transfer-guild: false
      upgrade-guild: false
      withdraw-money: true
      claim-land: false
      unclaim-land: false
      destroy: true
      place: true
      interact: true

  2:
    name: "Veteran"
    permission-node: "guilds.role.veteran"
    permissions:
      activate-buff: false
      add-ally: false
      ally-chat: true
      change-prefix: false
      chat: true
      demote: false
      deposit-money: true
      invite: true
      kick: false
      open-vault: true
      promote: false
      remove-ally: false
      remove-guild: false
      toggle-guild: false
      transfer-guild: false
      upgrade-guild: false
      withdraw-money: false
      claim-land: false
      unclaim-land: false
      destroy: true
      place: true
      interact: true
  3:
    name: "Member"
    permission-node: "guilds.role.member"
    permissions:
      activate-buff: false
      add-ally: false
      ally-chat: true
      change-prefix: false
      chat: true
      demote: false
      deposit-money: true
      invite: false
      kick: false
      open-vault: true
      promote: false
      remove-ally: false
      remove-guild: false
      toggle-guild: false
      transfer-guild: false
      upgrade-guild: false
      withdraw-money: false
      claim-land: false
      unclaim-land: false
      destroy: true
      place: true
      interact: true