name: Guilds
version: ${project.version}
main: me.glaremasters.guilds.Guilds
authors: [blockslayer22]
depend: [Vault]
description: Guilds
website: https://glaremasters.me/discord

commands:
  guild:
    aliases: [guilds, g]
    description: See the Guild commands
